---
version: '3'
services:
  dev-mysql:
    image: mysql:8.0.27
    container_name: dev-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    # volumes:
    #   - "./mysql-data:/var/lib/mysql"
  dev-postgres:
    image: postgres:15.5-alpine3.19
    container_name: dev-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  dev-jaeger:
    image: jaegertracing/all-in-one:1.51.0
    container_name: dev-jaeger
    ports:
      - 4318:4318
      - 14268:14268
      - 16686:16686
